INSERT OR IGNORE INTO areas (code, type, display_name) VALUES
    ('SettlersBossAlleyway', 'Boss Arena', 'Abandoned Port'),
    ('MavenBoss', 'Boss Arena', 'Absence of Mercy and Empathy'),
    ('BreachBossChaos', 'Boss Arena', 'Chayula''s Domain'),
    ('BreachBossChaos2', 'Boss Arena', 'Chayula''s Domain'),
    ('BreachBossChaos3', 'Boss Arena', 'Chayula''s Domain'),
    ('BreachBossChaos4', 'Boss Arena', 'Chayula''s Domain'),
    ('BreachBossChaos5', 'Boss Arena', 'Chayula''s Domain'),
    ('Synthesis_MapBoss', 'Boss Arena', 'Cortex'),
    ('BestiaryLeague_CrabBoss', 'Boss Arena', 'Craiceann''s Cove'),
    ('BreachBossLightning', 'Boss Arena', 'Esh''s Domain'),
    ('BreachBossLightning2', 'Boss Arena', 'Esh''s Domain'),
    ('BreachBossLightning3', 'Boss Arena', 'Esh''s Domain'),
    ('BreachBossLightning4', 'Boss Arena', 'Esh''s Domain'),
    ('BreachBossLightning5', 'Boss Arena', 'Esh''s Domain'),
    ('AtlasExilesBoss5', 'Boss Arena', 'Eye of the Storm'),
    ('BestiaryLeague_TigerBoss', 'Boss Arena', 'Farrul''s Den'),
    ('BestiaryLeague_ScorpBoss', 'Boss Arena', 'Fenumus'' Lair'),
    ('SettlersBossPirateCove', 'Boss Arena', 'Sailor''s Folly'),
    ('BestiaryLeague_BirdBoss', 'Boss Arena', 'Saqawal''s Roost'),
    ('SettlersBossFallenStar', 'Boss Arena', 'Starfall Crater'),
    ('BetrayalSafeHouseAssassins', 'Boss Arena', 'Syndicate Hideout'),
    ('BetrayalSafeHouseCaravan', 'Boss Arena', 'Syndicate Hideout'),
    ('BetrayalSafeHouseFortress', 'Boss Arena', 'Syndicate Hideout'),
    ('BetrayalSafeHouseLaboratory', 'Boss Arena', 'Syndicate Hideout'),
    ('MapAtziri2', 'Boss Arena', 'The Alluring Abyss'),
    ('MapAtziri1', 'Boss Arena', 'The Apex of Sacrifice'),
    ('FaridunLeagueBoss', 'Boss Arena', 'The Black Barya'),
    ('BreachBossCold', 'Boss Arena', 'Tul''s Domain'),
    ('BreachBossCold2_', 'Boss Arena', 'Tul''s Domain'),
    ('BreachBossCold4', 'Boss Arena', 'Tul''s Domain'),
    ('BreachBossPhysical', 'Boss Arena', 'Uul-Netol''s Domain'),
    ('BreachBossPhysical2', 'Boss Arena', 'Uul-Netol''s Domain'),
    ('BreachBossPhysical4', 'Boss Arena', 'Uul-Netol''s Domain'),
    ('BreachBossFire', 'Boss Arena', 'Xoph''s Domain'),
    ('BreachBossFire4', 'Boss Arena', 'Xoph''s Domain');
