INSERT OR IGNORE INTO areas (code, type, display_name) VALUES
    ('HideoutMountain', 'Hideout', 'Alpine Hideout'),
    ('HideoutHighGardens', 'Hideout', 'Arboreal Hideout'),
    ('HideoutAzuriteCave', 'Hideout', 'Azurite Cavern Hideout'),
    ('HideoutSlum', 'Hideout', 'Backstreet Hideout'),
    ('HideoutRuinedTemple', 'Hideout', 'Baleful Hideout'),
    ('HideoutBattleground', 'Hideout', 'Battle-scarred Hideout'),
    ('HideoutPrisonTower', 'Hideout', 'Brutal Hideout'),
    ('HideoutTemplarLab', 'Hideout', 'Cartographer''s Hideout'),
    ('HideoutShapersRealm', 'Hideout', 'Celestial Hideout'),
    ('HideoutSpace', 'Hideout', 'Celestial Nebula Hideout'),
    ('HideoutDaressoArena', 'Hideout', 'Champion''s Hideout'),
    ('HideoutBeach', 'Hideout', 'Coastal Hideout'),
    ('HideoutCoral', 'Hideout', 'Coral Hideout'),
    ('HideoutWorldTurtle', 'Hideout', 'Cosmic Turtle Hideout'),
    ('HideoutArenaMaven', 'Hideout', 'Crucible Hideout'),
    ('HideoutOasis', 'Hideout', 'Desert Hideout'),
    ('HideoutTwilightTemple', 'Hideout', 'Divided Hideout'),
    ('HideoutLibrary', 'Hideout', 'Enlightened Hideout'),
    ('HideoutMine', 'Hideout', 'Excavated Hideout'),
    ('HideoutDark', 'Hideout', 'Ghost-lit Graveyard Hideout'),
    ('HideoutIceberg', 'Hideout', 'Glacial Hideout'),
    ('HideoutDarkwood', 'Hideout', 'Glimmerwood Hideout'),
    ('HideoutHaunted', 'Hideout', 'Haunted Hideout'),
    ('HideoutSolaris', 'Hideout', 'Immaculate Hideout'),
    ('HideoutBlankAbyss', 'Hideout', 'Infinite Abyss Hideout'),
    ('HideoutInnocenceArena', 'Hideout', 'Innocent Hideout'),
    ('HideoutForest', 'Hideout', 'Lush Hideout'),
    ('HideoutBaths', 'Hideout', 'Luxurious Hideout'),
    ('HideoutMoonTemple', 'Hideout', 'Nocturnal Hideout'),
    ('HideoutGardens', 'Hideout', 'Overgrown Hideout'),
    ('HideoutArenaBlackStar_', 'Hideout', 'Polaric Hideout'),
    ('HideoutPrimevalRuins', 'Hideout', 'Primeval Hideout'),
    ('HideoutVeritaniaArena', 'Hideout', 'Redeemer''s Hideout'),
    ('HideoutRitualLeague', 'Hideout', 'Ritualist''s Hideout'),
    ('HideoutArch', 'Hideout', 'Robber''s Trench Hideout'),
    ('HideoutCrimsonTemple', 'Hideout', 'Sanguine Hideout'),
    ('HideoutArenaInfiniteHunger', 'Hideout', 'Seething Hideout'),
    ('HideoutShaperArena', 'Hideout', 'Shaped Hideout'),
    ('HideoutOssuary', 'Hideout', 'Skeletal Hideout'),
    ('HideoutCourts', 'Hideout', 'Stately Hideout'),
    ('HideoutCauseway', 'Hideout', 'Sunken Hideout'),
    ('HideoutSunspire', 'Hideout', 'Sunspire Hideout'),
    ('HideoutSynthesisHub', 'Hideout', 'Synthesis Hideout'),
    ('HideoutHasina', 'Hideout', 'Tavern Hideout'),
    ('HideoutDreadnought', 'Hideout', 'The Dreadnought Hideout'),
    ('HideoutLight', 'Hideout', 'Timekeeper''s Hideout'),
    ('HideoutAncestralTrial', 'Hideout', 'Trial of the Ancestors Hideout'),
    ('HideoutSewer', 'Hideout', 'Undercity Hideout'),
    ('HideoutFellshrine', 'Hideout', 'Unearthed Hideout'),
    ('HideoutBlankCity', 'Hideout', 'Urban Sprawl Hideout'),
    ('HideoutBlankGrass', 'Hideout', 'Vast Plains Hideout'),
    ('HideoutArenaElder', 'Hideout', 'Void Hideout');
