INSERT OR IGNORE INTO areas (code, type, display_name) VALUES
    ('AbyssLeague', 'Mechanic', 'Abyssal Depths'),
    ('AbyssLeague2', 'Mechanic', 'Abyssal Depths'),
    ('AbyssLeagueBoss', 'Mechanic', 'Abyssal Depths'),
    ('AbyssLeagueBoss2', 'Mechanic', 'Abyssal Depths'),
    ('Synthesis_MapGuardian1', 'Mechanic', 'Altered Distant Memory'),
    ('Labyrinth_Airlock', 'Mechanic', 'Aspirants'' Plaza'),
    ('Synthesis_MapGuardian2', 'Mechanic', 'Augmented Distant Memory'),
    ('Delve_Main', 'Mechanic', 'Azurite Mine'),
    ('ExpeditionCemetery', 'Mechanic', 'Cemetery'),
    ('LegionLeague3', 'Mechanic', 'Domain of Timeless Conflict'),
    ('LegionLeague4', 'Mechanic', 'Domain of Timeless Conflict'),
    ('CrucibleLeagueArea', 'Mechanic', 'Forge of the Titans'),
    ('ChayulaLeagueTowerBoss', 'Mechanic', 'Hive Colony'),
    ('2_11_endgame_town', 'Mechanic', 'Karui Shores'),
    ('KalguuranSettlersLeague', 'Mechanic', 'Kingsmarch'),
    ('BetrayalMastermindFight', 'Mechanic', 'Mastermind''s Lair'),
    ('ChayulaLeague', 'Mechanic', 'Monastery of the Keepers'),
    ('Synthesis_MapGuardian4', 'Mechanic', 'Rewritten Distant Memory'),
    ('ExpeditionRottingTemple', 'Mechanic', 'Rotting Temple'),
    ('SanctumCellar', 'Mechanic', 'Sanctum Archives'),
    ('SanctumNave', 'Mechanic', 'Sanctum Cathedral'),
    ('SanctumCrypt', 'Mechanic', 'Sanctum Necropolis'),
    ('SanctumVaults', 'Mechanic', 'Sanctum Vaults'),
    ('ExpeditionScrublands', 'Mechanic', 'Scrublands'),
    ('ExpeditionShipwreckReef', 'Mechanic', 'Shipwreck Reef'),
    ('Metamorphosis_Hub', 'Mechanic', 'Tane''s Laboratory'),
    ('SanctumFoyer_Fellshrine', 'Mechanic', 'The Forbidden Sanctum'),
    ('HallsOfTheDead_League', 'Mechanic', 'The Halls of the Dead'),
    ('LakePrototype', 'Mechanic', 'The Lake of Kalandra'),
    ('MavenHub', 'Mechanic', 'The Maven''s Crucible'),
    ('Menagerie_Hub', 'Mechanic', 'The Menagerie'),
    ('HeistHub', 'Mechanic', 'The Rogue Harbour'),
    ('HarvestLeagueBoss', 'Mechanic', 'The Sacred Grove'),
    ('Incursion_Temple10', 'Mechanic', 'The Temple of Atzoatl'),
    ('Incursion_Temple7_', 'Mechanic', 'The Temple of Atzoatl'),
    ('Incursion_Temple8', 'Mechanic', 'The Temple of Atzoatl'),
    ('Incursion_Temple9', 'Mechanic', 'The Temple of Atzoatl'),
    ('Synthesis_MapGuardian3', 'Mechanic', 'Twisted Distant Memory'),
    ('ExpeditionUtzaalOutskirts', 'Mechanic', 'Utzaal Outskirts'),
    ('ClassicTreasury_Cosmic', 'Mechanic', 'Voidborn Reliquary');

UPDATE areas SET subtype = 'Town' WHERE code = '2_11_endgame_town';
