package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

const (
	DefaultBind = "127.0.0.1"
	DefaultPort = 47652

	// FileName is poe-info-service's own external config file, the sole
	// store for user-facing config per ADR-006.
	FileName = "poe-info-service.toml"

	// DBFileName is poe-info-service's sole SQLite database — game history
	// (schema.sql) and the service's own internal bookkeeping (state,
	// api_cache) together in one file, resolved the same way as FileName so
	// both files sit side by side.
	DBFileName = "poe-info-service.db"
)

// Config is poe-info-service's own external configuration, persisted at
// <dir>/poe-info-service.toml. Per ADR-006, comments are generated from the
// `comment` struct tags below and rewritten fresh on every Save — they are
// never preserved from a prior hand edit.
type Config struct {
	Bind         string `toml:"bind" comment:"Address to bind the WebSocket server to."`
	Port         int    `toml:"port" comment:"TCP port to listen on."`
	DebugLogging bool   `toml:"debug_logging" comment:"Enable verbose debug logging."`
}

func Defaults() Config {
	return Config{Bind: DefaultBind, Port: DefaultPort, DebugLogging: false}
}

// ResolveDir picks the directory poe-info-service.toml is read from and
// written to: the current working directory if it contains a Justfile (i.e.
// the process was launched from the project root via `just run` or an IDE
// with CWD set to the repo), otherwise exeDir. Mirrors the dev convenience
// l2p-poe's own AppConfig::configPath() already applies to l2p-poe.toml, so
// both config files can sit side by side at the project root during
// development instead of deep inside the build tree.
func ResolveDir(exeDir string) string {
	if cwd, err := os.Getwd(); err == nil {
		if _, err := os.Stat(filepath.Join(cwd, "Justfile")); err == nil {
			return cwd
		}
	}
	return exeDir
}

// Load reads poe-info-service.toml from dir, returning hardcoded defaults for
// any key that is absent, and for the file as a whole if it is missing or
// unparseable.
func Load(dir string) Config {
	cfg := Defaults()
	data, err := os.ReadFile(filepath.Join(dir, FileName))
	if err != nil {
		return cfg
	}
	if err := toml.Unmarshal(data, &cfg); err != nil {
		return Defaults()
	}
	return cfg
}

// fileHeader is written above every generated config, since Save regenerates
// all comments from the `comment` struct tags on Config and discards
// whatever was there before — a human editing this file needs to know that
// up front, not discover it the next time something calls config.set.
const fileHeader = "" +
	"# This file is regenerated by poe-info-service on every write (e.g. a client's\n" +
	"# config.set call). Field comments below are regenerated too — any comments you\n" +
	"# add yourself will be removed the next time this file is saved. Values you set\n" +
	"# are preserved.\n\n"

// Save atomically (re)writes poe-info-service.toml in dir: it writes to a
// temp file in the same directory, then renames over the target, so a crash
// mid-write can't leave a corrupt or truncated file behind for a human to
// find during the exact outage this file exists to help diagnose.
func Save(dir string, cfg Config) error {
	body, err := toml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	data := append([]byte(fileHeader), body...)

	path := filepath.Join(dir, FileName)
	tmp, err := os.CreateTemp(dir, FileName+".tmp-*")
	if err != nil {
		return fmt.Errorf("create temp config: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("write temp config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("close temp config: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("rename temp config: %w", err)
	}
	return nil
}

// LoadChannelNames reads the [chat_channel_names] table (channel number ->
// user-defined label) from l2p-poe's own config toml, mirroring
// AppConfig::channelNames on the C++ side. Returns an empty map if the file
// is missing or the section is absent — channel labels are cosmetic, so any
// failure here is silent rather than fatal.
func LoadChannelNames(path string) map[int]string {
	names := map[int]string{}
	data, err := os.ReadFile(path)
	if err != nil {
		return names
	}

	inSection := false
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") {
			inSection = line == "[chat_channel_names]"
			continue
		}
		if !inSection {
			continue
		}
		kv := strings.SplitN(line, "=", 2)
		if len(kv) != 2 {
			continue
		}
		num, err := strconv.Atoi(strings.TrimSpace(kv[0]))
		if err != nil {
			continue
		}
		names[num] = strings.Trim(strings.TrimSpace(kv[1]), `"`)
	}
	return names
}
