package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
)

const (
	DefaultBind = "127.0.0.1"
	DefaultPort = 47652

	// FileName is poe-info-service's own external config file, the sole
	// store for user-facing config per ADR-006.
	FileName = "poe-info-service.toml"

	// DBFileName is poe-info-service's sole SQLite database — game history
	// (schema.sql) and the service's own internal bookkeeping (state,
	// api_cache) together in one file, resolved the same way as FileName so
	// both files sit side by side.
	DBFileName = "poe-info-service.db"
)

// Config is poe-info-service's own external configuration, persisted at
// <dir>/poe-info-service.toml. Per ADR-006, comments are generated from the
// `comment` struct tags below and rewritten fresh on every Save — they are
// never preserved from a prior hand edit.
type Config struct {
	Bind                 string   `toml:"bind" comment:"Address to bind the WebSocket server to."`
	Port                 int      `toml:"port" comment:"TCP port to listen on."`
	DebugLogging         bool     `toml:"debug_logging" comment:"Enable verbose debug logging."`
	InstallDirs          []string `toml:"install_dirs" comment:"PoE install directories to ingest Client.txt from."`
	AutoDetectInstallDir bool     `toml:"auto_detect_install_dir" comment:"Automatically add an install directory when a matching game process is seen running."`
	ExecutableNames      []string `toml:"executable_names" comment:"Executable basenames to look for when auto-detecting an install directory."`
	SteamIDs             []string `toml:"steam_ids" comment:"Steam64 IDs to track combined official + rich-presence data for (see the steam.presence WS method)."`
}

// DefaultExecutableNames is the canonical list of PoE executable basenames
// auto-detection matches against, and what a fresh install_dirs-less config
// starts with. Mirrors the old C++ AppConfig::knownExes() list.
func DefaultExecutableNames() []string {
	return []string{
		"PathOfExile_x64Steam.exe", "PathOfExileSteam.exe",
		"PathOfExile_x64.exe", "PathOfExile.exe",
		"PathOfExile_x64", "PathOfExile",
	}
}

func Defaults() Config {
	return Config{
		Bind:                 DefaultBind,
		Port:                 DefaultPort,
		DebugLogging:         false,
		AutoDetectInstallDir: true,
		ExecutableNames:      DefaultExecutableNames(),
	}
}

// ResolveDir picks the directory poe-info-service.toml is read from and
// written to: the current working directory if it contains a Justfile (i.e.
// the process was launched from the project root via `just run` or an IDE
// with CWD set to the repo), otherwise exeDir. Mirrors the dev convenience
// l2p-poe's own AppConfig::configPath() already applies to l2p-poe.toml, so
// both config files can sit side by side at the project root during
// development instead of deep inside the build tree.
func ResolveDir(exeDir string) string {
	if cwd, err := os.Getwd(); err == nil {
		if _, err := os.Stat(filepath.Join(cwd, "Justfile")); err == nil {
			return cwd
		}
	}
	return exeDir
}

// ResolveFile is ResolveDir plus the default config filename — the config
// file path used when neither --config nor --data-dir overrides it.
func ResolveFile(exeDir string) string {
	return filepath.Join(ResolveDir(exeDir), FileName)
}

// Load reads the config file at path, returning hardcoded defaults for any
// key that is absent, and for the file as a whole if it is missing or
// unparseable.
func Load(path string) Config {
	cfg := Defaults()
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg
	}
	if err := toml.Unmarshal(data, &cfg); err != nil {
		return Defaults()
	}
	return cfg
}

// fileHeader is written above every generated config, since Save regenerates
// all comments from the `comment` struct tags on Config and discards
// whatever was there before — a human editing this file needs to know that
// up front, not discover it the next time something calls config.set.
const fileHeader = "" +
	"# This file is regenerated by poe-info-service on every write (e.g. a client's\n" +
	"# config.set call). Field comments below are regenerated too — any comments you\n" +
	"# add yourself will be removed the next time this file is saved. Values you set\n" +
	"# are preserved.\n\n"

// Save atomically (re)writes the config file at path: it writes to a temp
// file in the same directory, then renames over the target, so a crash
// mid-write can't leave a corrupt or truncated file behind for a human to
// find during the exact outage this file exists to help diagnose. Creates
// the containing directory if it doesn't exist yet — --config/--data-dir
// may point somewhere that's never been used before.
func Save(path string, cfg Config) error {
	body, err := toml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	data := append([]byte(fileHeader), body...)

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create %q: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("create temp config: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("write temp config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("close temp config: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("rename temp config: %w", err)
	}
	return nil
}
