package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoadMissingFileReturnsDefaults(t *testing.T) {
	cfg := Load(filepath.Join(t.TempDir(), FileName))
	if cfg != Defaults() {
		t.Errorf("Load of missing file = %+v, want defaults %+v", cfg, Defaults())
	}
}

func TestSaveThenLoadRoundTrips(t *testing.T) {
	path := filepath.Join(t.TempDir(), FileName)
	want := Config{Bind: "0.0.0.0", Port: 12345, DebugLogging: true}

	if err := Save(path, want); err != nil {
		t.Fatalf("Save: %v", err)
	}
	got := Load(path)
	if got != want {
		t.Errorf("Load after Save = %+v, want %+v", got, want)
	}
}

func TestSaveAcceptsArbitraryFileName(t *testing.T) {
	path := filepath.Join(t.TempDir(), "custom-name.toml")
	want := Config{Bind: "0.0.0.0", Port: 12345, DebugLogging: true}

	if err := Save(path, want); err != nil {
		t.Fatalf("Save: %v", err)
	}
	got := Load(path)
	if got != want {
		t.Errorf("Load after Save = %+v, want %+v", got, want)
	}
}

func TestSaveGeneratesComments(t *testing.T) {
	path := filepath.Join(t.TempDir(), FileName)
	if err := Save(path, Defaults()); err != nil {
		t.Fatalf("Save: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.Contains(string(data), "# Enable verbose debug logging.") {
		t.Errorf("saved config missing generated field comment, got:\n%s", data)
	}
	if !strings.HasPrefix(string(data), "# This file is regenerated by poe-info-service") {
		t.Errorf("saved config missing leading auto-generated-comments notice, got:\n%s", data)
	}
}

func TestSaveLeavesNoTempFileBehind(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, FileName)
	if err := Save(path, Defaults()); err != nil {
		t.Fatalf("Save: %v", err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}
	if len(entries) != 1 || entries[0].Name() != FileName {
		names := make([]string, len(entries))
		for i, e := range entries {
			names[i] = e.Name()
		}
		t.Errorf("directory after Save = %v, want only %q", names, FileName)
	}
}

func TestResolveDirPrefersCwdWithJustfile(t *testing.T) {
	projectRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(projectRoot, "Justfile"), []byte(""), 0644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	exeDir := filepath.Join(t.TempDir(), "exe-dir")

	origWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	if err := os.Chdir(projectRoot); err != nil {
		t.Fatalf("Chdir: %v", err)
	}
	defer os.Chdir(origWd)

	if got := ResolveDir(exeDir); got != projectRoot {
		t.Errorf("ResolveDir = %q, want project root %q", got, projectRoot)
	}
}

func TestResolveDirFallsBackToExeDirWithoutJustfile(t *testing.T) {
	noJustfileDir := t.TempDir()
	exeDir := filepath.Join(t.TempDir(), "exe-dir")

	origWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	if err := os.Chdir(noJustfileDir); err != nil {
		t.Fatalf("Chdir: %v", err)
	}
	defer os.Chdir(origWd)

	if got := ResolveDir(exeDir); got != exeDir {
		t.Errorf("ResolveDir = %q, want exeDir %q", got, exeDir)
	}
}

func TestResolveFileJoinsResolveDirAndFileName(t *testing.T) {
	noJustfileDir := t.TempDir()
	exeDir := filepath.Join(t.TempDir(), "exe-dir")

	origWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	if err := os.Chdir(noJustfileDir); err != nil {
		t.Fatalf("Chdir: %v", err)
	}
	defer os.Chdir(origWd)

	want := filepath.Join(exeDir, FileName)
	if got := ResolveFile(exeDir); got != want {
		t.Errorf("ResolveFile = %q, want %q", got, want)
	}
}

func TestLoadUnparseableFileReturnsDefaults(t *testing.T) {
	path := filepath.Join(t.TempDir(), FileName)
	if err := os.WriteFile(path, []byte("not valid toml {{{"), 0644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	cfg := Load(path)
	if cfg != Defaults() {
		t.Errorf("Load of unparseable file = %+v, want defaults %+v", cfg, Defaults())
	}
}
